# Generated by Django 3.0.8 on 2020-07-14 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 7, 14, 12, 15, 0, 603386))),
            ],
        ),
    ]
